### ISSUE TITLE
Not showing up in confmanager and doesn't seem to be working with animal

### ISSUE THREAD

**Issue by GlitterHorn** [cosmocode/dokuwiki-plugin-aclplusregex#5]
Just installed this on my Greebo installation, and it doesn't appear to be doing anything. Not sure if that's because I haven't upgraded (which is mostly because I don't want to break everything I currently have working). The conf file doesn't show up in confmanager, and testing pages in a private browsing session shows the ACLs aren't taking effect.

Example of my conf:

```
tarot:spreads:at.+	@ALL	0
tarot:spreads:at.+	@user	1
```

**Comment by splitbrain** [comment]
:man_shrugging: it's very likely the plugin doesn't work on Greebo.
